name: Docker Image CI

on:
  push:
    branches: [ "remote_vnc_docker" ]
  pull_request:
    branches: [ "main" ]

jobs:
  my_job:
    name: deploy to staging
    runs-on: macos-latest
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag desktop_docker:$(date +%s)
